// Saudi city list (courts/offices), verbatim from the prototype CITIES const.
export const SAUDI_CITIES = [
  "الرياض",
  "جدة",
  "مكة المكرمة",
  "المدينة المنورة",
  "الدمام",
  "الخبر",
  "الأحساء",
  "بريدة",
  "حائل",
  "تبوك",
  "أبها",
  "خميس مشيط",
  "الطائف",
  "نجران",
  "جازان",
  "سكاكا",
  "عرعر",
  "ينبع",
  "الباحة",
] as const;
